POST http://localhost:3000/SV1/Saleshead/Insert/InsertColumnExist
Content-Type: application/json

{
	"VOUCHER_CANCELLED" : "",
	"REFERENCE" : "",
	"DATE" : "",
	"VOUCHERTYPE" : "",
	"PARTYNAME" : ""
}